#!/usr/bin/make

# Automatically generated xconfig: don't edit
# Mon Dec 19 17:49:47 2016

XCFG_BOARD = TX501S
XCFG_EXTERNAL_WEB_PATH = "http://src-server/downloads/packages"
XCFG_EXTERNAL_USE_zlib = y
XCFG_EXTERNAL_USE_lrzsz = y
XCFG_EXTERNAL_USE_dropbear = y
XCFG_EXTERNAL_USE_iniparser = y
XCFG_EXTERNAL_USE_cmdftp = y
XCFG_EXTERNAL_USE_libjansson = y
XCFG_EXTERNAL_USE_curl = y
XCFG_PLATFORM_GIT_HASH = ""
XCFG_PLATFORM_GIT_PATH = "evo@src-server:/home/data/git/neom2m/platform3/neom2m3.git"
XCFG_PLATFORM_USE_defaultsetting = y
XCFG_APPLICATION_GIT_PATH = "evo@src-server:/home/data/git/neom2m/app3"
XCFG_APPLICATION_USE_dmlib3 = y
XCFG_APPLICATION_GIT_HASH_dmlib3 = ""
XCFG_APPLICATION_USE_atlib3 = y
XCFG_APPLICATION_GIT_HASH_atlib3 = ""
XCFG_APPLICATION_USE_alive3 = y
XCFG_APPLICATION_GIT_HASH_alive3 = ""
XCFG_APPLICATION_USE_battchk3 = y
XCFG_APPLICATION_GIT_HASH_battchk3 = ""
XCFG_APPLICATION_USE_devtest3 = y
XCFG_APPLICATION_GIT_HASH_devtest3 = ""
XCFG_APPLICATION_USE_devinit3 = y
XCFG_APPLICATION_GIT_HASH_devinit3 = ""
XCFG_APPLICATION_USE_netchk3 = y
XCFG_APPLICATION_GIT_HASH_netchk3 = ""
XCFG_APPLICATION_USE_rssh3 = y
XCFG_APPLICATION_GIT_HASH_rssh3 = ""
XCFG_APPLICATION_USE_pathrun3 = y
XCFG_APPLICATION_GIT_HASH_pathrun3 = ""
XCFG_APPLICATION_USE_dlpkg3 = y
XCFG_APPLICATION_GIT_HASH_dlpkg3 = ""
XCFG_APPLICATION_USE_monchk3 = y
XCFG_APPLICATION_GIT_HASH_monchk3 = ""
XCFG_APPLICATION_USE_wdprog3 = y
XCFG_APPLICATION_GIT_HASH_wdprog3 = ""
XCFG_APPLICATION_USE_emer3 = y
XCFG_APPLICATION_GIT_HASH_emer3 = ""
XCFG_APPLICATION_USE_common-src3 = y
XCFG_APPLICATION_GIT_HASH_common-src3 = ""
XCFG_APPLICATION_USE_bootstrap3 = y
XCFG_APPLICATION_GIT_HASH_bootstrap3 = ""

